name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11', '17' ]
        go: [ '1.17', '1.18', '1.19' ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Test generated go code
        run: |
          cd generator-test-go
          go test ./testcases
