name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17' ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.Java }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go

      - name: Test generated go code
        run: |
          cd generator-test-go
          go test ./testcases
