# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - "created"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Copy artifacts to dist 
        run: |
          mkdir -p ${{ github.workspace }}/dist
          cp ${{ github.workspace }}/tool/target/tool-1.0-SNAPSHOT-compiler-with-beautifier.jar ${{ github.workspace }}/dist/asn1-compiler-with-google-java-format.jar
          cp ${{ github.workspace }}/tool/target/tool-1.0-SNAPSHOT-compiler-without-beautifier.jar ${{ github.workspace }}/dist/asn1-compiler.jar
          cp ${{ github.workspace }}/tool/target/tool-1.0-SNAPSHOT-converter.jar ${{ github.workspace }}/dist/asn1-converter.jar
          cp ${{ github.workspace }}/runtime/target/runtime-1.0-SNAPSHOT.jar ${{ github.workspace }}/dist/asn1-runtime.jar
          ls -l ${{ github.workspace }}/dist
      - name: Publish artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*"
 